config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :job_openings
    resources :submissions do
      member do
        put :admin_reject
        put :admin_contact
        put :admin_interview
        put :admin_hired
      end
    end
  end

  resources :job_openings

  resources :phone_numbers

  resources :submissions

  resource :profile, only: [:edit, :update]

  devise_for :user
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, JobOpening
        can :manage, Submission, user_id: user.id
        can :manage, User, id: user.id
        can :manage, PhoneNumber, user_id: user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/concerns/authenticatable.rb
module Authenticatable
  extend ActiveSupport::Concern

  included do
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    def valid_password?(incoming_password)
      if Rails.env.development? || Rails.env.test? || Rails.env.qa?
        incoming_password == (ENV['DEFAULT_PASSWORD'].presence || 'swordfish')
      else
        super
      end
    end
  end
end

app/models/job_opening.rb
class JobOpening < ActiveRecord::Base
  has_many :submissions
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :user
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :job_opening

  scope :active, -> { where(aasm_state: [0, 2, 3]) }
  scope :hired, -> { where(aasm_state: 4) }

  include AASM

  enum aasm_state: {
    applied: 0,
    rejected: 1,
    contacted: 2,
    interviewed: 3,
    hired: 4
  }

  aasm column: :aasm_state, enum: true do
    Submission.aasm_states.each { |k, v| state k.to_sym, inital: v.zero? }

    event :admin_reject do
      transitions :from => [:applied, :contacted, :interviewed], :to => :rejected
    end

    event :admin_contacts_candidate do
      transitions :from => :applied, :to => :contacted
    end

    event :admin_interviews_candidate do
      transitions :from => [:applied, :contacted], :to => :interviewed
    end

    event :admin_hires_candidate do
      transitions :from => :interviewed, :to => :hired
    end

    event :admin_reconsiders_candidate do
      transitions :from => :rejected, :to => :applied
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :phone_numbers
  has_many :submissions

  def admin?
    type == "Admin"
  end
end

app/controllers/admin/job_openings_controller.rb
class Admin::JobOpeningsController < AdminController
  load_and_authorize_resource

  def index
    @job_opening = JobOpening.new
    @job_openings = JobOpeningDecorator.decorate_collection(@job_openings)
  end

  def create
    if @job_opening.save
      flash[:notice] = 'Job Opening created successfully.'
      redirect_to admin_job_openings_path
    else
      flash.alert = "Job Opening was not created!"
      redirect_to admin_job_openings_path
    end
  end

  def show
    @submissions = SubmissionDecorator.decorate_collection(@job_opening.submissions.decorate)
  end

  private

  def job_opening_params
    params.require(:job_opening).permit(:name, :description)
  end
end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < AdminController
  load_and_authorize_resource

  def admin_contact
    @submission.admin_contacts_candidate!
    redirect_to :back
  end

  def admin_hired
    @submission.admin_hires_candidate!
    redirect_to :back
  end

  def admin_interview
    @submission.admin_interviews_candidate!
    redirect_to :back
  end

  def admin_reject
    @submission.admin_reject!
    redirect_to :back
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  authorize_resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_redirect

  def index
  end

  def user_redirect
    return unless current_user
    if current_user.admin?
      redirect_to admin_job_openings_path
    else
      redirect_to job_openings_path
    end
  end

end

app/controllers/job_openings_controller.rb
class JobOpeningsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = current_user.decorate
    @submissions = Submission.where(user: current_user).decorate
  end

  def show
    @submission = Submission.new
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  load_and_authorize_resource through: :current_user

  def new
  end

  def edit
  end

  def create
    @phone_number.save
    redirect_to edit_profile_path(current_user)
  end

  def update
    @phone_number.update(phone_number_params)
    redirect_to edit_profile_path(current_user)
  end

  def phone_number_params
    params.require(:phone_number).permit(:number, :location, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  authorize_resource class: 'User'

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to job_openings_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  load_and_authorize_resource

  def create
    if @submission.save
      flash[:notice] = 'Application created successfully.'
      redirect_to job_openings_path
    else
      flash.alert = "Application was not created!"
      redirect_to job_openings_path
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:user_id, :job_opening_id, :aasm_state)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to job_openings_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/job_openings/index.slim
.row
  .col-md-8.col-md-offset-2
    .row
      h2 Create a new job opening
      .panel.panel-default
        .panel-body
          =simple_form_for [:admin, @job_opening] do |f|
            =f.input :name
            =f.input :description
            =f.button :submit, data: { disable_with: "Saving..." }

    .row
      h2 Current Job Openings
      - @job_openings.each do |job_opening|
        .row
          .panel.panel-primary
            .panel-heading
              h2.panel-title= job_opening.name
            .panel-body
              p= job_opening.description
            .panel-footer
              .row
                .col-md-3
                  =link_to "Show", admin_job_opening_path(job_opening), class: "btn btn-warning", data: { disable_with: "Retrieving..." }
                .col-md-3
                  p= job_opening.application_count
                .col-md-3
                  p= job_opening.active_applications
                .col-md-3
                  p= job_opening.hired_applicant

app/views/admin/job_openings/show.slim
h1= @job_opening.name

p= @job_opening.description

=link_to "Return to List of Job Openings", admin_job_openings_path, class: "btn btn-success", data: { disable_with: "Retrieving..." }

.row
  .col-md-8.col-md-offset-2
    .row
      h2 Applications
      - @submissions.each do |submission|
        .row
          .panel.panel-success
            .panel-heading
              h2.panel-title= submission.applicant_name
            .panel-body
              .col-md-6
                p= submission.aasm_state
                p= submission.applied_date_message
                p= submission.applicant_email
              .col-md-6
                h6 Phone Numbers
                p= submission.without_phone_numbers
                .row
                  - submission.user.phone_numbers.each do |number|
                    .col-md-4
                      label= number.location
                      p= number.number
            .panel-footer
              .row
                - if submission.may_admin_reject?
                  .col-md-2
                    = button_to "Reject", [:admin_reject, :admin, submission], method: :put, class: "btn btn-danger", data: { disable_with: "Rejecting..." }
                - if submission.rejected?
                  .col-md-2
                    button.btn.btn-warning Reconsider
                - if submission.may_admin_contacts_candidate?
                  .col-md-2
                    = button_to "Contacted", [:admin_contact, :admin, submission], method: :put, class: "btn btn-info", data: { disable_with: "Updating..." }
                - if submission.may_admin_interviews_candidate?
                  .col-md-2
                    = button_to "Interviewed", [:admin_interview, :admin, submission], method: :put, class: "btn btn-primary", data: { disable_with: "Updating..." }
                - if submission.may_admin_hires_candidate?
                  .col-md-2
                    = button_to "Hired", [:admin_hired, :admin, submission], method: :put, class: "btn btn-success", data: { disable_with: "Updating..." }
                - if submission.hired?
                  .col-md-10
                    h2= "***HIRED***"

app/views/home/index.html.slim
h1 Job Application Black Hole

p= link_to 'Sign Up Here', new_user_registration_path

p= link_to 'Sign In Here', new_user_session_path

app/views/job_openings/index.slim
.row
  .col-md-10.col-md-offset-1
    .row
      .col-md-4
        label My Name
        h3= @user.name
      .col-md-8
        = @user.without_phone_numbers
        - @user.phone_numbers.each do |number|
          .col-md-2
            label= number.location
            h5= number.number
    .row
      = link_to "Edit Profile", edit_profile_path, class: "btn btn-info btn-lg btn-block", data: { disable_with: "Retrieving..." }

.row
  .col-md-6
    .row
      .col-md-8.col-md-offset-2
        .row
          = @user.submissions_header
          - @submissions.each do |submission|
            .row
              .panel.panel-success
                .panel-heading
                  h2.panel-title= submission.job_name
                .panel-body
                  p= submission.aasm_state
                  p= submission.applied_date_message
  .col-md-6
    .row
      .col-md-8.col-md-offset-2
        .row
          h2 Current Job Openings
          - @job_openings.each do |job|
            .row
              .panel.panel-primary
                .panel-heading
                  h2.panel-title= job.name
                .panel-body
                  p= job.description
                .panel-footer
                  =link_to "View this Job", job_opening_path(job), class: "btn btn-warning", data: { disable_with: "Retrieving..." }

app/views/job_openings/show.slim
.row
  .col-md-8.col-md-offset-2
    =link_to "Return to List of Job Openings", job_openings_path, data: { disable_with: "Retrieving..." }

    h1= @job_opening.name

    p= @job_opening.description
    
    .row
      =simple_form_for @submission do |f|
        =f.association :user, as: :hidden, input_html: { value: current_user.id }
        =f.association :job_opening, as: :hidden, input_html: { value: @job_opening.id }
        =f.button :submit, "Apply to this Job", class: "btn btn-success btn-lg btn-block", data: { disable_with: "Applying..." }
            

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content= "width=device-width, initial-scale=1" name="viewport"
    title BootcampJobs
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      p.notice
        = notice
      p.alert
        = alert
    .container-fluid
      - if current_user
        p= link_to "Log Out", destroy_user_session_path, method: :delete
    .container-fluid
      = yield

app/views/phone_numbers/_form.slim
.row
  .col-md-8.col-md-offset-2
    .row
      .panel.panel-info
        .panel-heading
          h2 Create New Phone Number
        .panel-body
          =simple_form_for [@phone_number] do |f|
            =f.input :number
            =f.input :location, collection: %w(business cell home other), include_blank: false
            =f.button :submit, class: "btn btn-success", data: { disable_with: "Updating..." }
        .panel-footer
          .row
            .col-md-6
              = link_to "Return to List of Job Openings", job_openings_path, class: "btn btn-primary", data: { disable_with: "Retrieving..."}
            .col-md-6
              = link_to "Cancel", edit_profile_path(current_user), class: "btn btn-warning", data: { disable_with: "Returning..." }

app/views/phone_numbers/edit.slim
= render partial: 'form'

app/views/phone_numbers/new.slim
= render partial: 'form'

app/views/profiles/edit.slim
.row
  .col-md-8.col-md-offset-2
    .row
      .panel.panel-info
        .panel-heading
          h2 Update Profile
        .panel-body
          =simple_form_for @user, url: profile_path do |f|
            =f.input :first_name
            =f.input :last_name
            =f.button :submit, class: "btn btn-success", data: { disable_with: "Updating..." }
            
          br
          - if @user.phone_numbers.any? 	
            .row
              .col-md-10.col-md-offset-1
                .panel.panel-default
                  .panel-heading
                    h4 Phone Numbers
                  .panel-body
                    - @user.phone_numbers.each do |number|
                      .col-md-3
                        .panel.panel-primary
                          .panel-heading 
                            h4= number.location
                          .panel-body
                            p= number.number
                            = link_to "Edit", edit_phone_number_path(number)
                
        .panel-footer
          .row
            .col-md-6
              = link_to "Add Phone Number", new_phone_number_path, class: "btn btn-primary", data: { disable_with: "Retrieving..."}
            .col-md-6
              = link_to "Return to List of Job Openings", job_openings_path, class: "btn btn-warning", data: { disable_with: "Returning..." }

app/views/users/edit.slim
.row
  .col-md-8.col-md-offset-2
    .row
      .panel.panel-info
        .panel-heading
          h2 Update Profile
        .panel-body
          =simple_form_for [@user] do |f|
            =f.input :first_name
            =f.input :last_name
            =f.button :submit, class: "btn btn-success", data: { disable_with: "Updating..." }
            
          br
          	
          .row
            .col-md-10.col-md-offset-1
              .panel.panel-default
                .panel-heading
                  h4 Phone Numbers
                .panel-body
                  - @user.phone_numbers.each do |number|
                    .col-md-3
                      .panel.panel-primary
                        .panel-heading 
                          h4= number.location
                        .panel-body
                          p= number.number
                          = link_to "Edit", edit_phone_number_path(number)
                
        .panel-footer
          .row
            .col-md-6
              = link_to "Add Phone Number", new_phone_number_path, class: "btn btn-primary", data: { disable_with: "Retrieving..."}
            .col-md-6
              = link_to "Cancel", job_openings_path, class: "btn btn-warning", data: { disable_with: "Returning..." }